import type { Metadata } from "next";
import localFont from "next/font/local";
//import { Inter } from "next/font/google";
import "./globals.css";
//const inter = Inter({ subsets: ["latin"] });
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import MainHeader from "@/components/main-header/main-header";
import { ThemeProvider } from "next-themes";
import Providers from "./providers";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const iranSans = localFont({
  src: [
    {
      path: "../public/fonts/IRANSansWeb.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/IRANSansWeb_Bold.woff2",
      weight: "bold",
      style: "normal",
    },
  ],
});
const iranSansFa = localFont({
  src: [
    {
      path: "../public/fonts/IRANSansWeb(FaNum).woff2",
      weight: "400",
      style: "normal",
    },

    {
      path: "../public/fonts/IRANSansWeb(FaNum)_Bold.woff2",
      weight: "bold",
      style: "normal",
    },
  ],
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body dir="rtl" className={iranSansFa.className}>
        <Providers>
          
            <MainHeader />
            {children}
          
        </Providers>
      </body>
    </html>
  );
}
